name: 'lsl lint'
description: 'Runs lslint on lsl files'
inputs:
  filepath:
    description: 'The path to run lslint on'
    required: true
    default: 'src/*.lsl'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.filepath }}
